language: generic 

sudo: required
services:
  - docker
before_install:
  - docker build -t vkozlov95/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vkozlov95/react-test npm tes

after_success:
  - docker build -t vkozlov95/multi-client ./client
  - docker build -t vkozlov95/multi-nginx ./nginx
  - docker build -t vkozlov95/multi-server ./server
  - docker build -t vkozlov95/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vkozlov95/multi-client
  - docker push vkozlov95/multi-nginx
  - docker push vkozlov95/multi-server
  - docker push vkozlov95/multi-worker